 
baseURL = "https://www.suburbzeroact.au/"


# This is a "one page"-website, so we do not need these kinds of pages...
disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT"]
author = "Garry Jolley-Rogers per S0"
defaultContentLanguage = "en"
relativeURLs = true
googleAnalytics = "G-SZBV9GNNKH"

# The name of this wonderful theme ;-).
theme = ["hugo-shortcode-roneo-collection", "hugo-cloak-email","hugo-scroll"]

# The "title" of your website
title = "Suburb Zero - electrify canberra"

[params]
    # A "copyright"-line to be added at the bottom of the page.
    # Hint: Markdown is supported in here as well. So you may e.g. add a link to your legal imprint-page.
    copyright = "© Suburb Zero ACT - electrify everything"

    # The "description" of your website. This is used in the meta data of your generated html.
    description = "Electrify Canberra"

    # The path to your "favicon". This should be a square (at least 32px x 32px) png-file.
    favicon = "images/favicon.png"

    # These "images" are used for the structured data templates. This will show up, when
    # services like Twitter or Slack want to generate a preview of a link to your site.
    # See https://gohugo.io/templates/internal#twitter-cards and
    # https://gohugo.io/templates/internal#open-graph.
    images = ["images/S0_web_header_16x9.png"]
    
    bannerImage = ["/images/S0_web_header_16x9.png"]
     
    
    # Another "title" :-). This one is used as the site_name on the Hugo's internal
    # opengraph structured data template.
    # See https://ogp.me/ and https://gohugo.io/templates/internal#open-graph.
    title = "Suburb Zero"

    # This theme will, by default, inject a design-by-line at the bottom of the page.
    # You can turn it off, but we would really appreciate if you don’t :-)
    hidedesignbyline = true

    [params.meta]
        keywords = "Canberra, energy, decarbonise, climate change, savings"

 
 
   
 
[taxonomies]
  series = 'series'